# Generated by Django 3.2.4 on 2022-04-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220412_0828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blocklist',
            new_name='IPRecord',
        ),
    ]
