# Generated by Django 3.2.13 on 2022-04-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220413_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Longitude',
            new_name='longitude',
        ),
    ]
