# Generated by Django 3.2.4 on 2022-04-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('Longitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('Latitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
            ],
        ),
    ]
