# Generated by Django 3.2.4 on 2022-04-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_auto_20220411_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ready'), (1, 'Progress'), (2, 'Done'), (3, 'Cancel'), (4, 'Delay')], default=0),
        ),
    ]
