# Generated by Django 3.2.4 on 2022-04-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_alter_schedule_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['start_at', 'end_at'], name='station_sch_start_a_6edb5a_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status'], name='status_idx'),
        ),
    ]
