# Generated by Django 3.2.13 on 2022-04-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_auto_20220412_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='Latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='Longitude',
            field=models.FloatField(null=True),
        ),
    ]
